import { createServerSupabaseClient } from "@/lib/supabase"
import { NextResponse } from "next/server"

export async function GET() {
  try {
    const supabase = createServerSupabaseClient()

    // Add missing columns directly
    const { error } = await supabase.rpc("execute_sql", {
      sql_query: `
        -- Add title column if it doesn't exist
        ALTER TABLE comics ADD COLUMN IF NOT EXISTS title TEXT;
        
        -- Add panel_descriptions column if it doesn't exist
        ALTER TABLE comics ADD COLUMN IF NOT EXISTS panel_descriptions JSONB;
        
        -- Add comments for documentation
        COMMENT ON COLUMN comics.title IS 'Title of the comic generated by GPT-4o-mini';
        COMMENT ON COLUMN comics.panel_descriptions IS 'Array of panel descriptions generated by GPT-4o-mini';
      `,
    })

    if (error) {
      console.error("Error adding columns:", error)
      return NextResponse.json({ error: error.message }, { status: 500 })
    }

    return NextResponse.json({ success: true, message: "Columns added successfully" })
  } catch (error) {
    console.error("Error fixing schema:", error)
    return NextResponse.json({ error: "Failed to fix schema" }, { status: 500 })
  }
}
