CREATE OR REPLACE FUNCTION add_comic_script_columns()
RETURNS void AS $$
BEGIN
  -- Add title column if it doesn't exist
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'comics' AND column_name = 'title') THEN
    ALTER TABLE comics ADD COLUMN title TEXT;
  END IF;

  -- Add panel_descriptions column if it doesn't exist
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'comics' AND column_name = 'panel_descriptions') THEN
    ALTER TABLE comics ADD COLUMN panel_descriptions JSONB;
  END IF;

  -- Add comments for documentation
  COMMENT ON COLUMN comics.title IS 'Title of the comic generated by GPT-4o-mini';
  COMMENT ON COLUMN comics.panel_descriptions IS 'Array of panel descriptions generated by GPT-4o-mini';
END;
$$ LANGUAGE plpgsql;
